### ISSUE TITLE
Possible Solution to Scar Apps?

### ISSUE THREAD

**Issue by Shugabuga** [Sn0wCh1ld/App-Installer#9]
This user from /r/sideloaded was able to remove the scar apps created by a non-jailbroken store, which might be useful for this project.

[Comment in Question](https://www.reddit.com/r/sideloaded/comments/6ksrgp/question_how_can_i_get_rid_of_these/djojp5s/)

Maybe the same method would work for scar apps created with App-Installer? I can't test as I don't have a paid developer account to use, nor have AppSync.

**Comment by Sn0wCh1ld** [comment]
I will take a look at this. The other method I had thought of would slow down the installation process so much that it wasn't worth it (downloading the IPA to the device, unpacking it, looking into the info.plist file and getting the bundle ID in order to install the app with the correct bundle ID).

**Comment by Sn0wCh1ld** [comment]
It worked. Now, if only there was a way to access that function from within App Installer.

**Comment by Shugabuga** [comment]
Pretty sure you can with URI schemes. Might try to make a button that opens that part of settings (forewarning: the code will be bad, as I suck with obj-c).

**Comment by Sn0wCh1ld** [comment]
Sounds good to me! The bundle ID of the scar app is com.appinstaller.app if you need it

**Comment by Shugabuga** [comment]
Okay. My plan is to have button to launch to relevant page in Settings under Install button

**Comment by Sn0wCh1ld** [comment]
As long as it works, don't worry about design, as we can fix that later. All we need is for the button to go straight to the scar app's page, making deletion much easier.

**Comment by Shugabuga** [comment]
Okay, so been working on it and it sorta works.

1) the URL scheme for storage on iOS 11 is unknown or nonexistent. I can't test on iOS 10 (only have a daily driver on iOS 11), but I think I got it right. You might want to double-check though.
2) I don't think you can go to a specific app's "storage page" so you can easily delete it (it might be possible, just not discovered yet though).

I think I am going to submit the pull request anyways, as it only helps (plus it's meant to go with AppSync, which is is on jailbroken [non-iOS 11] devices). The line dealing with the URL scheme is just one line, and can be easily updated in the future (by me or someone else).

Screenshot:
![img_9106](https://user-images.githubusercontent.com/10801851/27773412-24db4652-5f47-11e7-94a6-6d6857b410c4.PNG)
